name: 'test-egraph-module'

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - uses: actions/checkout@v4
            - name: Use node.js ${{ matrix.node-verison }}
            - uses: actions/setup-node@v4
              with: 
                node-version: ${{ matrix.node-version }}
            - name: npm ci, just build
              run: |
                cd egraph-app/
                npm ci
                npm run build
